#ifndef TOD_D3D9GRAPHICS_EXCEPTION_D3D9EXCEPTION_H
#define TOD_D3D9GRAPHICS_EXCEPTION_D3D9EXCEPTION_H

#include "core/exception.h"
#include "core/string.h"

namespace bzmag
{
namespace engine
{
    enum ENGINE_EXCEPTION
    {
        ENGINEEXCEPTIONCODE = 1000,

        ENGINEEXCEPTIONCODE_COULDNOTREGISTERWINDOW,
        ENGINEEXCEPTIONCODE_COULDNOTCREATEWINDOW,
        ENGINEEXCEPTIONCODE_TITLEISEMPTY,
        ENGINEEXCEPTIONCODE_OUTOFMEMORY,
        ENGINEEXCEPTIONCODE_INVALIDCALL,
    };
}
}

#endif // TOD_D3D9GRAPHICS_EXCEPTION_D3D9EXCEPTION_H
